---
- name: Deploy and run Maven JAR locally
  hosts: localhost
  vars:
    jar_file: "/root/hello-maven/target/hello-maven-1.0-SNAPSHOT.jar"
    dest_dir: "/opt/hello-maven"

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Copy JAR file locally
      copy:
        src: "{{ jar_file }}"
        dest: "{{ dest_dir }}/hello-maven.jar"
        mode: '0755'

    - name: Run the JAR file
      command: "java -jar {{ dest_dir }}/hello-maven.jar"
      async: 0
      poll: 0

