---
- name: Deploy and run Maven JAR locally
  hosts: localhost
  connection: local
  become: false

  tasks:
    - name: Ensure destination directory exists
      file:
        path: /tmp/hello-maven
        state: directory

    - name: Copy JAR file locally
      copy:
        src: hello-devops/target/hello-devops-1.0.jar
        dest: /tmp/hello-maven/hello-maven.jar
        mode: '0755'

    - name: Run application
      shell: java -jar /tmp/hello-maven/hello-maven.jar

