pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/devopsbeginner/maven_project.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'cd /hello-devops/app && mvn clean package'
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh 'cd /hello-devops/ansible && ansible-playbook -i inventory deploy.yml'
            }
        }
    }
}

