pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git ''
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'cd app && mvn clean package'
            }
        }

        stage('Deploy with Ansible') {
            steps {
                sh 'cd ansible && ansible-playbook -i inventory deploy.yml'
            }
        }
    }
}

